import localFont from "next/font/local";
import "./globals.css";
import Header from "./layout/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: "#0B192C",
          color: "white",
          width: "100vw",
        }}
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        <main style={{ width: "100vw" }}>{children}</main>
      </body>
    </html>
  );
}
